graph LR
    subgraph "Float Format"
        F1[28 bytes<br/>3D Mapping]
        F2[12 bytes<br/>Linear Accel]
        F3[40 bytes/update<br/>@ 50Hz = 2000 B/s]
    end
    
    subgraph "Fixed-Point Format"
        X1[15 bytes<br/>3D Mapping]
        X2[6 bytes<br/>Linear Accel]
        X3[21 bytes/update<br/>@ 50Hz = 1050 B/s]
    end
    
    F1 -->|"-46%"| X1
    F2 -->|"-50%"| X2
    F3 -->|"-48%"| X3