# Install script for directory: /home/ee/ncs/zephyr

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

# Set path to fallback-tool for dependency-resolution.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-objdump")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/ee/sensing_fw/build_primary/mcuboot/zephyr/arch/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/zephyr/lib/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/zephyr/soc/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/zephyr/boards/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/zephyr/subsys/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/zephyr/drivers/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/nrf/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/hostap/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/mcuboot/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/mbedtls/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/trusted-firmware-m/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/cjson/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/azure-sdk-for-c/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/cirrus-logic/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/openthread/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/suit-processor/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/memfault-firmware-sdk/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/canopennode/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/chre/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/lz4/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/nanopb/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/zscilib/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/cmsis/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/cmsis-dsp/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/cmsis-nn/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/fatfs/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/hal_nordic/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/hal_st/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/hal_tdk/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/hal_wurthelektronik/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/liblc3/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/libmetal/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/littlefs/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/loramac-node/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/lvgl/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/mipi-sys-t/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/nrf_wifi/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/open-amp/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/percepio/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/picolibc/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/segger/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/tinycrypt/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/uoscore-uedhoc/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/zcbor/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/nrfxlib/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/nrf_hw_models/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/modules/connectedhomeip/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/zephyr/kernel/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/zephyr/cmake/flash/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/zephyr/cmake/usage/cmake_install.cmake")
  include("/home/ee/sensing_fw/build_primary/mcuboot/zephyr/cmake/reports/cmake_install.cmake")

endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
if(CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "/home/ee/sensing_fw/build_primary/mcuboot/zephyr/install_local_manifest.txt"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
