/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SENSOR_DATA_MESSAGES_BHI360_SENSOR_MESSAGES_PB_H_INCLUDED
#define PB_SENSOR_DATA_MESSAGES_BHI360_SENSOR_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* --- Enums (BHI360 Specific) --- */
typedef enum _sensor_data_messages_BHI360MessageType {
    sensor_data_messages_BHI360MessageType_BHI360_UNKNOWN_MESSAGE_TYPE = 0, /* Default value, should always be 0 */
    sensor_data_messages_BHI360MessageType_BHI360_3D_DATA = 1,
    sensor_data_messages_BHI360MessageType_BHI360_STEP_COUNTER_DATA = 2
} sensor_data_messages_BHI360MessageType;

/* Struct definitions */
/* --- Message for 3D Vector Data (specific to BHI360) --- */
typedef struct _sensor_data_messages_Vector3f {
    float x;
    float y;
    float z;
} sensor_data_messages_Vector3f;

/* --- BHI360 3D Sensor Data Message --- */
typedef struct _sensor_data_messages_BHI360_3D_Data {
    bool has_acceleration;
    sensor_data_messages_Vector3f acceleration;
    bool has_angular_velocity;
    sensor_data_messages_Vector3f angular_velocity;
} sensor_data_messages_BHI360_3D_Data;

/* --- BHI360 Step Counter Data Message --- */
typedef struct _sensor_data_messages_BHI360_StepCounterData {
    uint32_t step_count;
    uint32_t activity_duration_s;
} sensor_data_messages_BHI360_StepCounterData;

/* --- BHI360 Combined Log Record (matches bhi360_log_record_t) --- */
typedef struct _sensor_data_messages_BHI360LogRecord {
    float quat_x;
    float quat_y;
    float quat_z;
    float quat_w;
    float quat_accuracy;
    float lacc_x;
    float lacc_y;
    float lacc_z;
    uint32_t step_count;
    uint16_t delta_ms; /* Delta time in milliseconds from previous packet (2 bytes, max 65535ms) */
    float gyro_x; /* Gyroscope X axis (rad/s) */
    float gyro_y; /* Gyroscope Y axis (rad/s) */
    float gyro_z; /* Gyroscope Z axis (rad/s) */
} sensor_data_messages_BHI360LogRecord;

/* BHI360 specific message for logging session metadata */
typedef struct _sensor_data_messages_BHI360SensingData {
    pb_callback_t firmware_version;
    uint32_t sampling_frequency;
    sensor_data_messages_BHI360MessageType message_type; /* Uses BHI360MessageType */
} sensor_data_messages_BHI360SensingData;

/* BHI360 specific message for marking the end of a logging session */
typedef struct _sensor_data_messages_BHI360SessionEnd {
    uint64_t uptime_ms;
} sensor_data_messages_BHI360SessionEnd;

/* --- Main Wrapper Message for BHI360 logs ---
 Renamed to be unique for BHI360 logs */
typedef struct _sensor_data_messages_BHI360LogMessage {
    pb_size_t which_payload;
    union _sensor_data_messages_BHI360LogMessage_payload {
        sensor_data_messages_BHI360_3D_Data bhi360_3d;
        sensor_data_messages_BHI360_StepCounterData bhi360_step_counter;
        sensor_data_messages_BHI360SensingData sensing_data;
        sensor_data_messages_BHI360SessionEnd session_end;
        sensor_data_messages_BHI360LogRecord bhi360_log_record; /* New: packed log record */
    } payload;
} sensor_data_messages_BHI360LogMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _sensor_data_messages_BHI360MessageType_MIN sensor_data_messages_BHI360MessageType_BHI360_UNKNOWN_MESSAGE_TYPE
#define _sensor_data_messages_BHI360MessageType_MAX sensor_data_messages_BHI360MessageType_BHI360_STEP_COUNTER_DATA
#define _sensor_data_messages_BHI360MessageType_ARRAYSIZE ((sensor_data_messages_BHI360MessageType)(sensor_data_messages_BHI360MessageType_BHI360_STEP_COUNTER_DATA+1))





#define sensor_data_messages_BHI360SensingData_message_type_ENUMTYPE sensor_data_messages_BHI360MessageType




/* Initializer values for message structs */
#define sensor_data_messages_Vector3f_init_default {0, 0, 0}
#define sensor_data_messages_BHI360_3D_Data_init_default {false, sensor_data_messages_Vector3f_init_default, false, sensor_data_messages_Vector3f_init_default}
#define sensor_data_messages_BHI360_StepCounterData_init_default {0, 0}
#define sensor_data_messages_BHI360LogRecord_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define sensor_data_messages_BHI360SensingData_init_default {{{NULL}, NULL}, 0, _sensor_data_messages_BHI360MessageType_MIN}
#define sensor_data_messages_BHI360SessionEnd_init_default {0}
#define sensor_data_messages_BHI360LogMessage_init_default {0, {sensor_data_messages_BHI360_3D_Data_init_default}}
#define sensor_data_messages_Vector3f_init_zero  {0, 0, 0}
#define sensor_data_messages_BHI360_3D_Data_init_zero {false, sensor_data_messages_Vector3f_init_zero, false, sensor_data_messages_Vector3f_init_zero}
#define sensor_data_messages_BHI360_StepCounterData_init_zero {0, 0}
#define sensor_data_messages_BHI360LogRecord_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define sensor_data_messages_BHI360SensingData_init_zero {{{NULL}, NULL}, 0, _sensor_data_messages_BHI360MessageType_MIN}
#define sensor_data_messages_BHI360SessionEnd_init_zero {0}
#define sensor_data_messages_BHI360LogMessage_init_zero {0, {sensor_data_messages_BHI360_3D_Data_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define sensor_data_messages_Vector3f_x_tag      1
#define sensor_data_messages_Vector3f_y_tag      2
#define sensor_data_messages_Vector3f_z_tag      3
#define sensor_data_messages_BHI360_3D_Data_acceleration_tag 2
#define sensor_data_messages_BHI360_3D_Data_angular_velocity_tag 3
#define sensor_data_messages_BHI360_StepCounterData_step_count_tag 2
#define sensor_data_messages_BHI360_StepCounterData_activity_duration_s_tag 3
#define sensor_data_messages_BHI360LogRecord_quat_x_tag 1
#define sensor_data_messages_BHI360LogRecord_quat_y_tag 2
#define sensor_data_messages_BHI360LogRecord_quat_z_tag 3
#define sensor_data_messages_BHI360LogRecord_quat_w_tag 4
#define sensor_data_messages_BHI360LogRecord_quat_accuracy_tag 5
#define sensor_data_messages_BHI360LogRecord_lacc_x_tag 6
#define sensor_data_messages_BHI360LogRecord_lacc_y_tag 7
#define sensor_data_messages_BHI360LogRecord_lacc_z_tag 8
#define sensor_data_messages_BHI360LogRecord_step_count_tag 9
#define sensor_data_messages_BHI360LogRecord_delta_ms_tag 10
#define sensor_data_messages_BHI360LogRecord_gyro_x_tag 11
#define sensor_data_messages_BHI360LogRecord_gyro_y_tag 12
#define sensor_data_messages_BHI360LogRecord_gyro_z_tag 13
#define sensor_data_messages_BHI360SensingData_firmware_version_tag 1
#define sensor_data_messages_BHI360SensingData_sampling_frequency_tag 2
#define sensor_data_messages_BHI360SensingData_message_type_tag 3
#define sensor_data_messages_BHI360SessionEnd_uptime_ms_tag 1
#define sensor_data_messages_BHI360LogMessage_bhi360_3d_tag 2
#define sensor_data_messages_BHI360LogMessage_bhi360_step_counter_tag 3
#define sensor_data_messages_BHI360LogMessage_sensing_data_tag 4
#define sensor_data_messages_BHI360LogMessage_session_end_tag 5
#define sensor_data_messages_BHI360LogMessage_bhi360_log_record_tag 6

/* Struct field encoding specification for nanopb */
#define sensor_data_messages_Vector3f_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define sensor_data_messages_Vector3f_CALLBACK NULL
#define sensor_data_messages_Vector3f_DEFAULT NULL

#define sensor_data_messages_BHI360_3D_Data_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  acceleration,      2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  angular_velocity,   3)
#define sensor_data_messages_BHI360_3D_Data_CALLBACK NULL
#define sensor_data_messages_BHI360_3D_Data_DEFAULT NULL
#define sensor_data_messages_BHI360_3D_Data_acceleration_MSGTYPE sensor_data_messages_Vector3f
#define sensor_data_messages_BHI360_3D_Data_angular_velocity_MSGTYPE sensor_data_messages_Vector3f

#define sensor_data_messages_BHI360_StepCounterData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   step_count,        2) \
X(a, STATIC,   SINGULAR, UINT32,   activity_duration_s,   3)
#define sensor_data_messages_BHI360_StepCounterData_CALLBACK NULL
#define sensor_data_messages_BHI360_StepCounterData_DEFAULT NULL

#define sensor_data_messages_BHI360LogRecord_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    quat_x,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    quat_y,            2) \
X(a, STATIC,   SINGULAR, FLOAT,    quat_z,            3) \
X(a, STATIC,   SINGULAR, FLOAT,    quat_w,            4) \
X(a, STATIC,   SINGULAR, FLOAT,    quat_accuracy,     5) \
X(a, STATIC,   SINGULAR, FLOAT,    lacc_x,            6) \
X(a, STATIC,   SINGULAR, FLOAT,    lacc_y,            7) \
X(a, STATIC,   SINGULAR, FLOAT,    lacc_z,            8) \
X(a, STATIC,   SINGULAR, UINT32,   step_count,        9) \
X(a, STATIC,   SINGULAR, UINT32,   delta_ms,         10) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_x,           11) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_y,           12) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_z,           13)
#define sensor_data_messages_BHI360LogRecord_CALLBACK NULL
#define sensor_data_messages_BHI360LogRecord_DEFAULT NULL

#define sensor_data_messages_BHI360SensingData_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   firmware_version,   1) \
X(a, STATIC,   SINGULAR, UINT32,   sampling_frequency,   2) \
X(a, STATIC,   SINGULAR, UENUM,    message_type,      3)
#define sensor_data_messages_BHI360SensingData_CALLBACK pb_default_field_callback
#define sensor_data_messages_BHI360SensingData_DEFAULT NULL

#define sensor_data_messages_BHI360SessionEnd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   uptime_ms,         1)
#define sensor_data_messages_BHI360SessionEnd_CALLBACK NULL
#define sensor_data_messages_BHI360SessionEnd_DEFAULT NULL

#define sensor_data_messages_BHI360LogMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,bhi360_3d,payload.bhi360_3d),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,bhi360_step_counter,payload.bhi360_step_counter),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,sensing_data,payload.sensing_data),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,session_end,payload.session_end),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,bhi360_log_record,payload.bhi360_log_record),   6)
#define sensor_data_messages_BHI360LogMessage_CALLBACK NULL
#define sensor_data_messages_BHI360LogMessage_DEFAULT NULL
#define sensor_data_messages_BHI360LogMessage_payload_bhi360_3d_MSGTYPE sensor_data_messages_BHI360_3D_Data
#define sensor_data_messages_BHI360LogMessage_payload_bhi360_step_counter_MSGTYPE sensor_data_messages_BHI360_StepCounterData
#define sensor_data_messages_BHI360LogMessage_payload_sensing_data_MSGTYPE sensor_data_messages_BHI360SensingData
#define sensor_data_messages_BHI360LogMessage_payload_session_end_MSGTYPE sensor_data_messages_BHI360SessionEnd
#define sensor_data_messages_BHI360LogMessage_payload_bhi360_log_record_MSGTYPE sensor_data_messages_BHI360LogRecord

extern const pb_msgdesc_t sensor_data_messages_Vector3f_msg;
extern const pb_msgdesc_t sensor_data_messages_BHI360_3D_Data_msg;
extern const pb_msgdesc_t sensor_data_messages_BHI360_StepCounterData_msg;
extern const pb_msgdesc_t sensor_data_messages_BHI360LogRecord_msg;
extern const pb_msgdesc_t sensor_data_messages_BHI360SensingData_msg;
extern const pb_msgdesc_t sensor_data_messages_BHI360SessionEnd_msg;
extern const pb_msgdesc_t sensor_data_messages_BHI360LogMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sensor_data_messages_Vector3f_fields &sensor_data_messages_Vector3f_msg
#define sensor_data_messages_BHI360_3D_Data_fields &sensor_data_messages_BHI360_3D_Data_msg
#define sensor_data_messages_BHI360_StepCounterData_fields &sensor_data_messages_BHI360_StepCounterData_msg
#define sensor_data_messages_BHI360LogRecord_fields &sensor_data_messages_BHI360LogRecord_msg
#define sensor_data_messages_BHI360SensingData_fields &sensor_data_messages_BHI360SensingData_msg
#define sensor_data_messages_BHI360SessionEnd_fields &sensor_data_messages_BHI360SessionEnd_msg
#define sensor_data_messages_BHI360LogMessage_fields &sensor_data_messages_BHI360LogMessage_msg

/* Maximum encoded size of messages (where known) */
/* sensor_data_messages_BHI360SensingData_size depends on runtime parameters */
/* sensor_data_messages_BHI360LogMessage_size depends on runtime parameters */
#define SENSOR_DATA_MESSAGES_BHI360_SENSOR_MESSAGES_PB_H_MAX_SIZE sensor_data_messages_BHI360LogRecord_size
#define sensor_data_messages_BHI360LogRecord_size 65
#define sensor_data_messages_BHI360SessionEnd_size 11
#define sensor_data_messages_BHI360_3D_Data_size 34
#define sensor_data_messages_BHI360_StepCounterData_size 12
#define sensor_data_messages_Vector3f_size       15

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
