/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "bhi360_sensor_messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sensor_data_messages_Vector3f, sensor_data_messages_Vector3f, AUTO)


PB_BIND(sensor_data_messages_BHI360_3D_Data, sensor_data_messages_BHI360_3D_Data, AUTO)


PB_BIND(sensor_data_messages_BHI360_StepCounterData, sensor_data_messages_BHI360_StepCounterData, AUTO)


PB_BIND(sensor_data_messages_BHI360LogRecord, sensor_data_messages_BHI360LogRecord, AUTO)


PB_BIND(sensor_data_messages_BHI360SensingData, sensor_data_messages_BHI360SensingData, AUTO)


PB_BIND(sensor_data_messages_BHI360SessionEnd, sensor_data_messages_BHI360SessionEnd, AUTO)


PB_BIND(sensor_data_messages_BHI360LogMessage, sensor_data_messages_BHI360LogMessage, AUTO)





