graph LR
    A[log] --> B[list<br/>Show all logs]
    A --> C[decode]
    C --> D[foot<br/>Latest foot log]
    C --> E[bhi360<br/>Latest BHI log]
    C --> F[file PATH<br/>Specific file]
    A --> G[delete_all<br/>Remove all logs]