/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "activity_messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sensor_data_messages_ActivityData, sensor_data_messages_ActivityData, AUTO)


PB_BIND(sensor_data_messages_ActivitySensingData, sensor_data_messages_ActivitySensingData, AUTO)


PB_BIND(sensor_data_messages_ActivitySessionEnd, sensor_data_messages_ActivitySessionEnd, AUTO)


PB_BIND(sensor_data_messages_ActivityLogMessage, sensor_data_messages_ActivityLogMessage, AUTO)





