
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "/home/ee/ncs/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/ee/ncs/zephyr/cmake/modules/zephyr_default.cmake:142 (include)"
      - "/home/ee/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ee/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:9 (find_package)"
    message: |
      The target system is: Generic - 4.0.99 - arm
      The host system is: Linux - 5.15.167.4-microsoft-standard-WSL2 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/local/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/local/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/ee/ncs/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/ee/ncs/zephyr/cmake/modules/zephyr_default.cmake:142 (include)"
      - "/home/ee/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ee/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:9 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      /opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld: /opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib/libc.a(lib_a-exit.o): in function `exit':
      exit.c:(.text.exit+0x34): undefined reference to `_exit'
      collect2: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/local/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/local/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/ee/ncs/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/ee/ncs/zephyr/cmake/modules/zephyr_default.cmake:142 (include)"
      - "/home/ee/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ee/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:9 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is GNU, found in:
        /home/ee/sensing_fw/build_primary/ipc_radio/CMakeFiles/4.0.2/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/local/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/local/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/ee/ncs/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/ee/ncs/zephyr/cmake/modules/zephyr_default.cmake:142 (include)"
      - "/home/ee/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ee/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:9 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-g++ 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      /opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld: /opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib/libc.a(lib_a-exit.o): in function `exit':
      exit.c:(.text.exit+0x34): undefined reference to `_exit'
      collect2: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/local/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/local/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/ee/ncs/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/ee/ncs/zephyr/cmake/modules/zephyr_default.cmake:142 (include)"
      - "/home/ee/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ee/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:9 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-g++ 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is GNU, found in:
        /home/ee/sensing_fw/build_primary/ipc_radio/CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1271 (message)"
      - "/usr/local/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/ee/ncs/zephyr/cmake/modules/kernel.cmake:134 (enable_language)"
      - "/home/ee/ncs/zephyr/cmake/modules/zephyr_default.cmake:142 (include)"
      - "/home/ee/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ee/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:9 (find_package)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      arm-zephyr-eabi-gcc (Zephyr SDK 0.17.0) 12.2.0
      Copyright (C) 2022 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-4.0/Modules/CheckIncludeFiles.cmake:141 (try_compile)"
      - "/home/ee/ncs/modules/hal/libmetal/libmetal/cmake/depends.cmake:33 (check_include_files)"
      - "/home/ee/ncs/modules/hal/libmetal/libmetal/CMakeLists.txt:17 (include)"
    checks:
      - "Looking for include file stdatomic.h"
    directories:
      source: "/home/ee/sensing_fw/build_primary/ipc_radio/CMakeFiles/CMakeScratch/TryCompile-vnC3VV"
      binary: "/home/ee/sensing_fw/build_primary/ipc_radio/CMakeFiles/CMakeScratch/TryCompile-vnC3VV"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/ee/ncs/nrf/cmake/modules;/home/ee/ncs/zephyr/cmake/modules;/home/ee/ncs/modules/hal/libmetal/libmetal/cmake;/home/ee/ncs/modules/hal/libmetal/libmetal/cmake/modules;/home/ee/ncs/modules/hal/libmetal/libmetal/cmake/platforms"
    buildResult:
      variable: "HAVE_STDATOMIC_H"
      cached: true
      stdout: |
        Change Dir: '/home/ee/sensing_fw/build_primary/ipc_radio/CMakeFiles/CMakeScratch/TryCompile-vnC3VV'
        
        Run Build Command(s): /usr/bin/ninja -v cmTC_adc9e
        [1/2] /opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc   -c -o CMakeFiles/cmTC_adc9e.dir/HAVE_STDATOMIC_H.c.obj -c /home/ee/sensing_fw/build_primary/ipc_radio/CMakeFiles/CMakeScratch/TryCompile-vnC3VV/HAVE_STDATOMIC_H.c
        [2/2] : && /opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -c  CMakeFiles/cmTC_adc9e.dir/HAVE_STDATOMIC_H.c.obj -o cmTC_adc9e   && :
        arm-zephyr-eabi-gcc: warning: CMakeFiles/cmTC_adc9e.dir/HAVE_STDATOMIC_H.c.obj: linker input file unused because linking not done
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-4.0/Modules/CheckIncludeFiles.cmake:141 (try_compile)"
      - "/home/ee/ncs/modules/lib/open-amp/open-amp/cmake/depends.cmake:19 (check_include_files)"
      - "/home/ee/ncs/modules/lib/open-amp/open-amp/CMakeLists.txt:18 (include)"
    checks:
      - "Looking for include file fcntl.h"
    directories:
      source: "/home/ee/sensing_fw/build_primary/ipc_radio/CMakeFiles/CMakeScratch/TryCompile-buvn5b"
      binary: "/home/ee/sensing_fw/build_primary/ipc_radio/CMakeFiles/CMakeScratch/TryCompile-buvn5b"
    cmakeVariables:
      CMAKE_C_FLAGS: " -Wall -Wextra"
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/ee/ncs/nrf/cmake/modules;/home/ee/ncs/zephyr/cmake/modules;/home/ee/ncs/modules/lib/open-amp/open-amp/cmake;/home/ee/ncs/modules/lib/open-amp/open-amp/cmake/modules;/home/ee/ncs/modules/lib/open-amp/open-amp/cmake/platforms"
    buildResult:
      variable: "HAVE_FCNTL_H"
      cached: true
      stdout: |
        Change Dir: '/home/ee/sensing_fw/build_primary/ipc_radio/CMakeFiles/CMakeScratch/TryCompile-buvn5b'
        
        Run Build Command(s): /usr/bin/ninja -v cmTC_5e3b4
        [1/2] /opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc   -Wall -Wextra -c -o CMakeFiles/cmTC_5e3b4.dir/HAVE_FCNTL_H.c.obj -c /home/ee/sensing_fw/build_primary/ipc_radio/CMakeFiles/CMakeScratch/TryCompile-buvn5b/HAVE_FCNTL_H.c
        [2/2] : && /opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -Wall -Wextra -c  CMakeFiles/cmTC_5e3b4.dir/HAVE_FCNTL_H.c.obj -o cmTC_5e3b4   && :
        arm-zephyr-eabi-gcc: warning: CMakeFiles/cmTC_5e3b4.dir/HAVE_FCNTL_H.c.obj: linker input file unused because linking not done
        
      exitCode: 0
...
